name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t fan0223/auth .
      - name: Login to DockerHub Registry
        run:
            echo ${‌{ secrets.DOCKER_TOKEN }} | docker login -u ${‌{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
            DOCKERHUB_USER: ${‌{ secrets.DOCKER.USERNAME }}
            DOCKERHUB_PASSWORD: ${‌{ secrets.DOCKER.TOKEN }}
      - run: docker push fan0223/auth
